package dun

import "strings"

// OpenItem is a not-yet-converted TODO or GOAL line pulled from
// today's ledger (FR-07).
type OpenItem struct {
	Category string // "TODO" or "GOAL"
	Text     string
}

// convertedSuffix marks a DONE line as having been generated by
// converting an open TODO/GOAL, so parseOpenItems can recognize it and
// exclude the original from the "open" list. Kept as an exact,
// greppable suffix rather than a separate marker file, to stay
// append-only/plain-text (per project's ledger design).
func convertedSuffix(category string) string {
	return " (via " + category + ")"
}

// parseLedgerLine splits a ledger line "[HH:MM:SS] CATEGORY text"
// into category and text. Returns ok=false if the line doesn't look
// like a well-formed ledger entry.
func parseLedgerLine(line string) (category, text string, ok bool) {
	parts := strings.SplitN(line, " ", 3)
	if len(parts) < 3 {
		return "", "", false
	}
	return parts[1], parts[2], true
}

// parseOpenItems scans ledger lines for TODO/GOAL entries that have
// not yet been converted to DONE (via recordConvertedDone), in
// first-seen order.
func parseOpenItems(lines []string) []OpenItem {
	var open []OpenItem
	converted := make(map[string]bool) // "CATEGORY\x00text" -> true

	for _, line := range lines {
		cat, text, ok := parseLedgerLine(line)
		if !ok {
			continue
		}
		if cat == "DONE" {
			for _, srcCat := range []string{"TODO", "GOAL"} {
				if suffix := convertedSuffix(srcCat); strings.HasSuffix(text, suffix) {
					orig := strings.TrimSuffix(text, suffix)
					converted[srcCat+"\x00"+orig] = true
				}
			}
			continue
		}
		if cat == "TODO" || cat == "GOAL" {
			open = append(open, OpenItem{Category: cat, Text: text})
		}
	}

	var result []OpenItem
	for _, item := range open {
		if !converted[item.Category+"\x00"+item.Text] {
			result = append(result, item)
		}
	}
	return result
}

// getOpenItems returns today's open (unconverted) TODO/GOAL items.
func getOpenItems() []OpenItem {
	return parseOpenItems(readLedgerLines())
}

// recordConvertedDone logs a DONE entry referencing an original
// TODO/GOAL item's text, marking it as converted (FR-07). The
// original line is left untouched (append-only ledger design).
func recordConvertedDone(item OpenItem) {
	recordActivity(item.Text+convertedSuffix(item.Category), "DONE")
}
